### PR TITLE
fix: add cxx_standard to avoid c++ check error

### PR DESCRIPTION
**Pull request by homalozoa**
As the solution at https://github.com/orocos/orocos_kinematics_dynamics/issues/441 , I add an arg to set the CXX_STANDARD to 11 for building project "orocos_kdl'.

### CODE REVIEW

**Comment by cottsay** [comment]
It would be nice if the developer still had the ability to change the `CXX_STANDARD` explicitly without modifying the source code. What would you think of setting `CMAKE_CXX_STANDARD` to `11` on the project only if it isn't otherwise defined, and then passing that along to the `orocos_kdl` build?

**Comment by clalancette** [comment]
> It would be nice if the developer still had the ability to change the `CXX_STANDARD` explicitly without modifying the source code. What would you think of setting `CMAKE_CXX_STANDARD` to `11` on the project only if it isn't otherwise defined, and then passing that along to the `orocos_kdl` build?

Yeah, agreed.  In point of fact, I'd make the default C++17 (that's what we use anywhere), but conditional on it not being set by the user.

**Comment by homalozoa** [comment]
> It would be nice if the developer still had the ability to change the `CXX_STANDARD` explicitly without modifying the source code. What would you think of setting `CMAKE_CXX_STANDARD` to `11` on the project only if it isn't otherwise defined, and then passing that along to the `orocos_kdl` build?

Agreed. Good idea! I'll modify to that.

**Comment by clalancette** [comment]
Pulls: https://github.com/ros2/orocos_kdl_vendor/pull/30
Gist: https://gist.githubusercontent.com/clalancette/1321d88724b4cb30559b927293800f01/raw/71f05fc797d5090a995cc6249c0512315bc7d174/ros2.repos
BUILD args:  --packages-above-and-dependencies orocos_kdl_vendor
TEST args:  --packages-above orocos_kdl_vendor
ROS Distro: rolling
Job: ci_launcher
ci_launcher ran: https://ci.ros2.org/job/ci_launcher/14724
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/22022/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/16278/)
* Linux-rhel [Build Status](http://ci.ros2.org/job/ci_linux-rhel/1540/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/22752/)

**Review by clalancette — APPROVED** [review]

**Comment by clalancette** [comment]
So, unfortunately, on Windows this ended up causing a regression.  I guess it is probably because we specified C++17 instead of C++11, and orocos_kdl is not ready for that?  I guess we can set this back to C++11 by default, but let's add a comment saying why it is different than every other core package.

**Comment by homalozoa** [comment]
> So, unfortunately, on Windows this ended up causing a regression. I guess it is probably because we specified C++17 instead of C++11, and orocos_kdl is not ready for that? I guess we can set this back to C++11 by default, but let's add a comment saying why it is different than every other core package.

Sure. I already changed it back. Let's check it again.

**Comment by clalancette** [comment]
Pulls: https://github.com/ros2/orocos_kdl_vendor/pull/30
Gist: https://gist.githubusercontent.com/clalancette/a6815558ddb29f472b38b508851298ae/raw/71f05fc797d5090a995cc6249c0512315bc7d174/ros2.repos
BUILD args:  --packages-above-and-dependencies orocos_kdl_vendor
TEST args:  --packages-above orocos_kdl_vendor
ROS Distro: rolling
Job: ci_launcher
ci_launcher ran: https://ci.ros2.org/job/ci_launcher/14727
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/22025/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/16282/)
* Linux-rhel [Build Status](http://ci.ros2.org/job/ci_linux-rhel/1543/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/22755/)

**Pull request merged**
